---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This is simple Hello World component written in Python."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        com.example.IPCComponent:mqttproxy:1:
          policyDescription: Allows access to subscribe to all topics.
          operations:
            - aws.greengrass#SubscribeToIoTCore
            - aws.greengrass#PublishToIoTCore
          resources:
            - "*"
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/greengrass-helloworld.zip"
        Unarchive: ZIP
    Lifecycle:
      Install:
        RequiresPrivilege: true
        script: |-
          python3 -m pip install awsiotsdk
          python3 -m pip install greengrasssdk
      Run: 
        RequiresPrivilege: true
        script: |-          
          python3 -u {artifacts:decompressedPath}/greengrass-helloworld/main.py {configuration:/Message}
      